export type ReferenceType = "moc" | "official_set" | "gaozhu_direction";

export type ReferenceSample = {
  id: string;
  title: string;
  referenceType: ReferenceType;
  themeTags: string[];
  styleTags: string[];
  sizeTags: string[];
  audienceTags: string[];
  featureTags: string[];
  whyRelevant: string;
  takeaway: string;
  link: string | null;
  sourceLabel: string;
};

export const referenceSamples: ReferenceSample[] = [
  {
    id: "ref-moc-001",
    title: "城市维修机甲中型场景",
    referenceType: "moc",
    themeTags: ["城市", "机甲"],
    styleTags: ["工业", "可动"],
    sizeTags: ["中"],
    audienceTags: ["青少年", "成人收藏"],
    featureTags: ["模块化", "可动", "场景化", "标准件友好"],
    whyRelevant: "与城市机甲类题材接近，结构与展示兼顾。",
    takeaway: "可借鉴机甲与场景分体设计，先稳结构再加装饰。",
    link: null,
    sourceLabel: "MOC 社区样本"
  },
  {
    id: "ref-moc-002",
    title: "复古科幻轨道站展示版",
    referenceType: "moc",
    themeTags: ["科幻", "建筑"],
    styleTags: ["复古", "展示向"],
    sizeTags: ["大", "展示级"],
    audienceTags: ["成人收藏"],
    featureTags: ["场景化", "定制件较多", "发光"],
    whyRelevant: "适合展示向高体量方案的视觉组织参考。",
    takeaway: "建议先确定主视觉轴线，再收敛次级装饰层。",
    link: null,
    sourceLabel: "MOC 展示样本"
  },
  {
    id: "ref-moc-003",
    title: "海岸救援微场景协作包",
    referenceType: "moc",
    themeTags: ["城市", "载具"],
    styleTags: ["简洁", "场景化"],
    sizeTags: ["小", "中"],
    audienceTags: ["儿童", "亲子"],
    featureTags: ["标准件友好", "场景化", "模块化"],
    whyRelevant: "与亲子向救援题材在体量和玩法上相近。",
    takeaway: "优先保留主任务流程，减少非核心道具堆叠。",
    link: null,
    sourceLabel: "MOC 社区样本"
  },
  {
    id: "ref-moc-004",
    title: "工业仓库可动装卸车",
    referenceType: "moc",
    themeTags: ["城市", "载具"],
    styleTags: ["工业", "可动"],
    sizeTags: ["中"],
    audienceTags: ["青少年", "成人收藏"],
    featureTags: ["可动", "标准件友好", "模块化"],
    whyRelevant: "与工业载具方向的结构与成本平衡思路一致。",
    takeaway: "可借鉴统一连接件规格，降低维护和替换成本。",
    link: null,
    sourceLabel: "MOC 结构样本"
  },
  {
    id: "ref-moc-005",
    title: "奇幻塔楼模块拼接",
    referenceType: "moc",
    themeTags: ["奇幻", "建筑"],
    styleTags: ["奇幻", "展示向"],
    sizeTags: ["中", "大"],
    audienceTags: ["青少年", "成人收藏"],
    featureTags: ["模块化", "场景化", "定制件较多"],
    whyRelevant: "可用于奇幻建筑方向的模块划分参考。",
    takeaway: "先收敛模块接口，再逐段增加视觉细节更稳妥。",
    link: null,
    sourceLabel: "MOC 社区样本"
  },
  {
    id: "ref-moc-006",
    title: "家居感街角咖啡屋",
    referenceType: "moc",
    themeTags: ["城市", "建筑"],
    styleTags: ["家居感", "简洁"],
    sizeTags: ["小", "中"],
    audienceTags: ["亲子", "成人收藏"],
    featureTags: ["场景化", "标准件友好"],
    whyRelevant: "适合家居感小体量场景的落地节奏参考。",
    takeaway: "建议先固定建筑骨架，再补窗框与街景细节。",
    link: null,
    sourceLabel: "MOC 生活化样本"
  },
  {
    id: "ref-moc-007",
    title: "机甲武装背包系统",
    referenceType: "moc",
    themeTags: ["机甲", "科幻"],
    styleTags: ["工业", "可动"],
    sizeTags: ["中", "大"],
    audienceTags: ["青少年", "成人收藏"],
    featureTags: ["可动", "模块化", "标准件友好"],
    whyRelevant: "可动结构与模块替换策略有直接借鉴价值。",
    takeaway: "优先统一背包接口规格，可提高版本迭代可控性。",
    link: null,
    sourceLabel: "MOC 机甲样本"
  },
  {
    id: "ref-moc-008",
    title: "低件数高速巡逻艇",
    referenceType: "moc",
    themeTags: ["载具", "城市"],
    styleTags: ["简洁", "展示向"],
    sizeTags: ["小"],
    audienceTags: ["儿童", "青少年"],
    featureTags: ["标准件友好", "可动"],
    whyRelevant: "适合小体量载具方向的零件收敛参考。",
    takeaway: "更稳妥的做法是先控件数，再提升轮廓识别度。",
    link: null,
    sourceLabel: "MOC 轻量样本"
  },
  {
    id: "ref-off-001",
    title: "城市工程维修中心",
    referenceType: "official_set",
    themeTags: ["城市", "建筑"],
    styleTags: ["工业", "场景化"],
    sizeTags: ["中"],
    audienceTags: ["儿童", "亲子"],
    featureTags: ["标准件友好", "模块化", "场景化"],
    whyRelevant: "官方套装在场景玩法与结构平衡上更成熟。",
    takeaway: "可借鉴任务分区设计，提升玩法清晰度。",
    link: null,
    sourceLabel: "官方套装"
  },
  {
    id: "ref-off-002",
    title: "科幻机甲对战组",
    referenceType: "official_set",
    themeTags: ["机甲", "科幻"],
    styleTags: ["可动", "工业"],
    sizeTags: ["小", "中"],
    audienceTags: ["青少年"],
    featureTags: ["可动", "标准件友好"],
    whyRelevant: "适合参考可动机构与件数控制方式。",
    takeaway: "建议优先固定可动关节数量，避免无效复杂度。",
    link: null,
    sourceLabel: "官方套装"
  },
  {
    id: "ref-off-003",
    title: "模块化街景商店",
    referenceType: "official_set",
    themeTags: ["城市", "建筑"],
    styleTags: ["展示向", "家居感"],
    sizeTags: ["大", "展示级"],
    audienceTags: ["成人收藏"],
    featureTags: ["模块化", "场景化", "标准件友好"],
    whyRelevant: "与展示型建筑在分层和模块接口思路上相近。",
    takeaway: "可借鉴分层拆装策略，提高后续改造灵活度。",
    link: null,
    sourceLabel: "官方套装"
  },
  {
    id: "ref-off-004",
    title: "奇幻城堡基础版",
    referenceType: "official_set",
    themeTags: ["奇幻", "建筑"],
    styleTags: ["奇幻", "展示向"],
    sizeTags: ["中", "大"],
    audienceTags: ["青少年", "成人收藏"],
    featureTags: ["场景化", "模块化"],
    whyRelevant: "在奇幻主题中兼顾玩法与展示的成熟做法较多。",
    takeaway: "建议先固定主塔与外墙比例，再叠加主题装饰。",
    link: null,
    sourceLabel: "官方套装"
  },
  {
    id: "ref-off-005",
    title: "创意车辆三合一套装",
    referenceType: "official_set",
    themeTags: ["载具"],
    styleTags: ["简洁", "可动"],
    sizeTags: ["小", "中"],
    audienceTags: ["儿童", "青少年"],
    featureTags: ["标准件友好", "模块化", "可动"],
    whyRelevant: "适合参考件数效率和多形态结构复用。",
    takeaway: "可借鉴共用底盘思路，减少非必要专用件。",
    link: null,
    sourceLabel: "官方套装"
  },
  {
    id: "ref-off-006",
    title: "未来实验室场景组",
    referenceType: "official_set",
    themeTags: ["科幻", "建筑"],
    styleTags: ["工业", "展示向"],
    sizeTags: ["中"],
    audienceTags: ["青少年", "成人收藏"],
    featureTags: ["场景化", "标准件友好", "发光"],
    whyRelevant: "科幻建筑方向的功能分区和视觉节奏可直接借鉴。",
    takeaway: "建议优先划分功能区，再填充装置细节。",
    link: null,
    sourceLabel: "官方套装"
  },
  {
    id: "ref-off-007",
    title: "海岸巡逻救援站",
    referenceType: "official_set",
    themeTags: ["城市", "载具"],
    styleTags: ["场景化", "简洁"],
    sizeTags: ["中"],
    audienceTags: ["儿童", "亲子"],
    featureTags: ["场景化", "标准件友好", "模块化"],
    whyRelevant: "与救援类场景在任务流程和载具关系上高度接近。",
    takeaway: "更稳妥的做法是让载具与站点形成闭环任务路径。",
    link: null,
    sourceLabel: "官方套装"
  },
  {
    id: "ref-off-008",
    title: "高级展示机甲底座组合",
    referenceType: "official_set",
    themeTags: ["机甲", "科幻"],
    styleTags: ["展示向", "工业"],
    sizeTags: ["大", "展示级"],
    audienceTags: ["成人收藏"],
    featureTags: ["可动", "场景化", "标准件友好"],
    whyRelevant: "可参考展示机甲的底座支撑与比例分配。",
    takeaway: "建议优先确认底座承重，再扩展上层视觉件。",
    link: null,
    sourceLabel: "官方套装"
  },
  {
    id: "ref-gz-001",
    title: "中体量机甲先行打样路径",
    referenceType: "gaozhu_direction",
    themeTags: ["机甲", "城市"],
    styleTags: ["工业", "可动"],
    sizeTags: ["中", "大"],
    audienceTags: ["青少年", "成人收藏"],
    featureTags: ["标准件友好", "模块化", "可动"],
    whyRelevant: "适合机甲类项目从概念走向可打样的收敛路径。",
    takeaway: "建议先锁定关节与承重主链，再分批验证外观模块。",
    link: null,
    sourceLabel: "高砖经验样本"
  },
  {
    id: "ref-gz-002",
    title: "展示向建筑的成本收敛策略",
    referenceType: "gaozhu_direction",
    themeTags: ["建筑", "城市"],
    styleTags: ["展示向", "家居感"],
    sizeTags: ["大", "展示级"],
    audienceTags: ["成人收藏"],
    featureTags: ["标准件友好", "场景化"],
    whyRelevant: "适合大体量展示项目平衡视觉与成本。",
    takeaway: "先保主视觉立面，再压缩重复装饰层级更稳妥。",
    link: null,
    sourceLabel: "高砖经验样本"
  },
  {
    id: "ref-gz-003",
    title: "亲子向场景套组标准化建议",
    referenceType: "gaozhu_direction",
    themeTags: ["城市", "载具"],
    styleTags: ["简洁", "场景化"],
    sizeTags: ["小", "中"],
    audienceTags: ["儿童", "亲子"],
    featureTags: ["标准件友好", "模块化"],
    whyRelevant: "亲子向方案更依赖标准件与步骤友好度。",
    takeaway: "建议优先统一连接件和步骤节奏，降低拼搭门槛。",
    link: null,
    sourceLabel: "高砖经验样本"
  },
  {
    id: "ref-gz-004",
    title: "奇幻建筑模块化量产收敛",
    referenceType: "gaozhu_direction",
    themeTags: ["奇幻", "建筑"],
    styleTags: ["奇幻", "展示向"],
    sizeTags: ["中", "大"],
    audienceTags: ["青少年", "成人收藏"],
    featureTags: ["模块化", "标准件友好", "场景化"],
    whyRelevant: "奇幻题材常见装饰过重，适合先做结构收敛。",
    takeaway: "建议先明确模块接口，再控制异形和装饰件比例。",
    link: null,
    sourceLabel: "高砖经验样本"
  },
  {
    id: "ref-gz-005",
    title: "科幻场景首轮风险拆解模板",
    referenceType: "gaozhu_direction",
    themeTags: ["科幻", "建筑", "机甲"],
    styleTags: ["工业", "展示向"],
    sizeTags: ["中", "大"],
    audienceTags: ["青少年", "成人收藏"],
    featureTags: ["模块化", "场景化", "标准件友好"],
    whyRelevant: "适合复杂科幻方案的首轮风险拆分。",
    takeaway: "更稳妥的做法是先做结构子模块验证，再拼装整体验证。",
    link: null,
    sourceLabel: "高砖经验样本"
  },
  {
    id: "ref-gz-006",
    title: "载具系列接口统一策略",
    referenceType: "gaozhu_direction",
    themeTags: ["载具", "城市"],
    styleTags: ["工业", "简洁"],
    sizeTags: ["小", "中"],
    audienceTags: ["儿童", "青少年"],
    featureTags: ["标准件友好", "可动", "模块化"],
    whyRelevant: "适合载具方向在迭代期做平台化收敛。",
    takeaway: "建议优先统一底盘与接口，可提高系列化可控性。",
    link: null,
    sourceLabel: "高砖经验样本"
  },
  {
    id: "ref-gz-007",
    title: "展示级套组分段打样路径",
    referenceType: "gaozhu_direction",
    themeTags: ["建筑", "科幻"],
    styleTags: ["展示向", "复古"],
    sizeTags: ["展示级"],
    audienceTags: ["成人收藏"],
    featureTags: ["模块化", "标准件友好", "场景化"],
    whyRelevant: "展示级项目更需要分段打样与分层收敛。",
    takeaway: "建议按承重层、外壳层、装饰层分三段验证。",
    link: null,
    sourceLabel: "高砖经验样本"
  },
  {
    id: "ref-gz-008",
    title: "低风险可动结构优先级清单",
    referenceType: "gaozhu_direction",
    themeTags: ["机甲", "载具"],
    styleTags: ["可动", "工业"],
    sizeTags: ["中"],
    audienceTags: ["青少年", "成人收藏"],
    featureTags: ["可动", "标准件友好"],
    whyRelevant: "适合可动方案降低首轮结构失败概率。",
    takeaway: "建议优先保留高价值可动点，次要关节后置迭代。",
    link: null,
    sourceLabel: "高砖经验样本"
  }
];
